# to manually assign a static port
server:
  port: 8761

spring:
  application:
    name: discovery-server # for unique service name

# Eureka is a service registry and discovery server that is part of the Netflix OSS
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: discovery-server