spring:
  application:
    name: invoice-service
  data:

    elasticsearch:
      repositories:
        enabled: true


  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888