spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/turkcellbootcamp2/microservices-t2/configs/dev

        #default-label: master
        #git:
        #  uri: file:///C:/turkcellbootcamp2/microservices-t2/configs/prod
        #uri: https://github.com/kalayciburak-instruction/config-server-t2-prod
  profiles:
    active: native
server:
  port: 8888